apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.name }}
  labels:
    app: my-java-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      containers:
        - name: {{ .Chart.name }}
          image: "{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
