apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.name }}
  labels:
    app: my-java-app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: my-java-app
