apiVersion: v1
kind: Service
metadata:
  name: "green"
  labels:
    app: "green"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: "{{ .Values.image.tag }}"
