apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}_{{ .Values.image.tag }}"
  labels:
    app: "{{ .Release.Name }}_{{ .Values.image.tag }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: "{{ .Release.Name }}_{{ .Values.image.tag }}"
